services:
  db:
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1m
      timeout: 10s
      retries: 3

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - ${MH_PORT}:1025
      - ${MH_WEB}:8025

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5m
      timeout: 10s
      retries: 3

volumes:
  pg_data: {}
